# Generated by Django 4.2.7 on 2023-12-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_sizevarient_sizevariant_and_more'),
        ('accounts', '0003_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='products.product'),
        ),
    ]
