# Generated by Django 4.2.7 on 2023-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cartitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
