# Generated by Django 5.0 on 2023-12-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizevarient_product_size_varient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVarient',
            new_name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_varient',
            new_name='size_variant',
        ),
    ]
